---
- name: Installing Gitlab for all nodes
  hosts: masterNode
  become: yes

  tasks:

#copy over storage class file 
# apply it, make it default 
    - name: Download Helm installation script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0700'

    - name: Set execute permission on Helm installation script
      file:
        path: /tmp/get_helm.sh
        mode: '0700'

    - name: Execute Helm installation script
      command: /tmp/get_helm.sh

#add secret here 
    - name: Add GitLab Helm repository
      command:
        cmd: helm repo add gitlab https://charts.gitlab.io/

    - name: Add AWS EBS CSI Driver Helm repository
      command:
        cmd: helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver

    - name: Update Helm repositories
      command:
        cmd: helm repo update

# install driver with helm 
# wait for driver to get created?? 
# install gitlab helm  





# 1) create IAM user for the driver with the permissions 
# 2) create secret with credentials to that IAM account. driver accepts by default. get creds from generated file from terraform 
# 3) deply with helm helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver, helm repo update, helm upgrade --install aws-ebs-csi-driver \
#    --namespace kube-system \
#    aws-ebs-csi-driver/aws-ebs-csi-driver
# 4) 
